title: Data Privacy and Ethics
logo: /assets/img/logo.gif
description: Monday August 15th, 2022 (1:00 - 4:00 pm PT), Tuesday August 16th, 2022 (1:00 - 4:00 pm PT)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
